GET http://localhost:3333/tasks

###

POST http://localhost:3333/tasks

{
  "title": "Estudar React",
  "description": "Trilha RN"
}

###

PUT http://localhost:3333/tasks/30d1995d-6389-4246-a2b7-baa8b9ab396a

{
  "description": "Trilha REACT JS"
}

###

PATCH http://localhost:3333/tasks/db840350-6afb-4a1a-a3f0-c6c57e9a8142/complete

###

DELETE http://localhost:3333/tasks/d4436755-8786-4367-9149-4685595736a0