GET http://localhost:3333/tasks

###

POST http://localhost:3333/tasks

{
  "title": "Estudar RN",
  "description": "Trilha RN"
}

###

PUT http://localhost:3333/tasks/6672fe74-7184-4f8e-b7f8-1a82926e1045

{
  "description": "Trilha Flutter"
}

###

PATCH http://localhost:3333/tasks/6672fe74-7184-4f8e-b7f8-1a82926e1045/complete

###

DELETE http://localhost:3333/tasks/713a7873-1f22-4cf6-8c0c-b0e180e287cd